config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

MovieDino::Application.routes.draw do

  root to: 'pages#index'

  resources :sessions, defaults: { format: 'json'}
  resources :users, except: [:show]
  resources :outings, except: [:show]
  resources :attendees, except: [:index, :new]

  match '/profile', to: 'users#show',      as: 'profile'
  match '/loading', to: 'outings#loading', as: 'loading'
  match '/status',  to: 'outings#status',  as: 'status'
  match '/start',   to: 'outings#cache'
  match '/success', to: 'outings#success'
  match '/thanks',  to: 'attendees#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure',            to:  redirect('/')
  match 'signout',                 to: 'sessions#destroy', as: 'signout'
  match '/:provider/auth',         to: 'sessions#create'

  match '/about', to: 'pages#about', as: 'about'

  mount Sidekiq::Web, at: "/admin/sidekiq", :constraints => AdminConstraint.new
  ###################################
  #please dont move this, it's greedy.
  #maybe we use /m/:link instead?
  match '/:link', to: 'attendees#new', :as => 'outings_form' #outings_form(outing.link)
end

app/views/shared/_errors.html.erb
<% if flash[:notice] %>
  <div class='errors'>
     <br>
     <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="row">
  <div class="large-12 columns">
    <div id="credits">
      <p>
        MAC-MAN STUDIOS <small>presents</small>
        <br>
        <small>in association with</small> DEV BOOTCAMP <small>a site unfortunately not directed by</small> MICHAEL BAY <small>or</small> CHRISTOPHER NOLAN "MOVIE DINO"
        </br>
        <small>lead developer</small> MAC BROWNING <small>product manager</small> ANGIE BUI <small>information architect</small> VINCENT STORME <small>lead designer</small> ROBBY FAIRCLOUGH
        </br>
        <small>created on location in </small> SAN FRANCISCO CALIFORNIA
      </p>
      <div id="date">
        <ul>
          <li><span class="rating"><a href='http://github.com/seanbr/movie_dino'><i class="icon-github"></i></a></span><span class="rating">RATED G FOR GITHUB</li>
          <li><span class="date"><%= Time.now().strftime('%b %d') %></span></li>
          <li><span class="twitter"><a href="http://www.twitter.com/moviedino"><i class="icon-twitter"></i></a></span></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-wrapper">
      <div class="logo-nav">
        <ul class="nav">
          <li id="settings">
            <a href="/" id="logo">DINO</a>
          </li>
          <li>
            <%= link_to 'ABOUT', about_path %>
          </li>
        </ul>
      </div>
      <div class="user-nav">
        <ul class="nav">
          <li id="search">
            <%= form_for :outing, url: start_path, method: 'get', :html => {id: 'zipcode_form'} do |f|  %>
              <button type="button" name="search_button" id="search_button"><i class="icon-ticket"></i></button>
              <%= text_field_tag 'zipcode', nil, pattern: '\d{5}', required: true, id: 'search_text', maxlength: 5, placeholder: 'ZIP CODE' %>
              <%= f.submit "I'm hidden", style: "display:none" %>
            <% end %>
          </li>
          <li id="options">
          <% if current_user %>
            <a href="#" id='current_user'><%= current_user.first_name %></a>
            <ul class="subnav">
              <li><a href="/profile"><i class="icon-calendar"></i>My Events</a></li>
              <li><%= link_to "SIGN OUT", signout_path, id: "sign_out" %></li>
            </ul>
          <% else %>
            <a href="#">Sign In</a>
            <ul class="subnav">
              <li> <%= link_to "Facebook", "/auth/facebook", rel: :external, id: "sign_in" %></li>
            </ul>
          <% end %>
          </li>
        </div>
      </div>
    </ul>
  </div>
</div>

<script>
  jQuery(document).ready(function ($) {

    $( '#search_button' ).click( function(event) {
      $( '#new_outing' ).submit();
    });

    $( '#search_button, #search_text' ).hover( function() {
      $( '#search_text' ).css( { width : '200px', paddingLeft : '15px' } );
    }, function() {
      $( '#search_text' ).css( { width : '0px', paddingLeft : '0px' } );
    });

    $( '#search_text' ).on( 'click', function() {
      $(this).css( { width : '200px', paddingLeft : '15px' } ).unbind( 'mouseleave' );
    });

  });
</script>

app/views/shared/_theater.html.erb
<% @outing.get_theaters.each do |theater|  %>
  <h1><%= theater.name %></h1>
  <% @theater_selections = @outing.selections.where(:theater_id => theater.id) %>
  <ul>
    <% @outing.get_movies.each do |movie|  %>
      <% @theater_movies = @theater_selections.where(movie_id: movie.id) %>
      <% unless @theater_movies.empty? %>
        <li><h6><%= movie.display_title %></h6>
          <% @theater_movies.each do |selection| %>
            <%= display_time selection.time %>
          <% end %>
        </p>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_theater_selection.html.erb
<div class="theater-listing">
  
  <% @outing.get_theaters.each do |theater|  %>
  
  <div class='theater panel' data-theater-id='<%= theater.id %>'>
    <h3><%= theater.name %></h3>
    
    <% @theater_selections = @outing.selections.where(:theater_id => theater.id) %>
    
    <ul class="movie-listings">
      
      <% @outing.get_movies.each do |movie|  %>
      <% @theater_movies = @theater_selections.where(movie_id: movie.id).order(:time) %>
      <% unless @theater_movies.empty? %>
      
      <div class="row">
        <li class='movie' data-movie-id='<%= movie.id %>' data-theater-id='<%= theater.id %>'>
          <div class="large-2 columns">
            <img src="<%= movie.poster_med %>" />
            </div>
            <div class="large-10 columns">
            <h6><%= movie.display_title %></h6>
            <ul>
              <% @theater_movies.each do |selection| %>
              <li class='showtime-checkbox' data-selection-id='<%= selection.id %>'><%= check_box_tag(selection.movie.title, selection.id,
              checked = false, name: "selections[#{selection.movie.title}_#{selection.id}]") %><%=display_time selection.time %></li>
              <% end %>
            </ul>
          </div>
        </li>
      </div>

      <% end %>
      <% end %>

    </ul>
  </div>

  <% end %>

</div>