config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

MovieDino::Application.routes.draw do

  root to: 'pages#index'

  resources :sessions, defaults: { format: 'json'}
  resources :users, except: [:show]
  resources :outings, except: [:show]
  resources :attendees, except: [:index, :new]

  match '/profile', to: 'users#show',      as: 'profile'
  match '/loading', to: 'outings#loading', as: 'loading'
  match '/status',  to: 'outings#status',  as: 'status'
  match '/start',   to: 'outings#cache'
  match '/success', to: 'outings#success'
  match '/thanks',  to: 'attendees#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure',            to:  redirect('/')
  match 'signout',                 to: 'sessions#destroy', as: 'signout'
  match '/:provider/auth',         to: 'sessions#create'

  match '/about', to: 'pages#about', as: 'about'

  mount Sidekiq::Web, at: "/admin/sidekiq", :constraints => AdminConstraint.new
  ###################################
  #please dont move this, it's greedy.
  #maybe we use /m/:link instead?
  match '/:link', to: 'attendees#new', :as => 'outings_form' #outings_form(outing.link)
end

app/models/outing.rb
class Outing < ActiveRecord::Base
  attr_accessor :showtimes
  attr_accessible :user, :user_id, :result_date, :selections, :showtimes,
                  :result_date

  has_many :selections
  has_many :attendees
  has_many :showtimes, through: :selections
  has_many :theaters, through: :selections
  has_many :movies, through: :selections
  has_many :times, through: :selections

  belongs_to :user
  before_create :create_selections
  after_create :save_result_date, :outing_emails!
  before_validation :generate_link, on: :create

  validates_uniqueness_of :link

  def date
    self.selections.order('time DESC').last.time.to_date.to_formatted_s(:long_ordinal)
  end

  def weekday_date
    self.selections.order('time DESC').last.time.strftime('%A, %b %d')
  end

  def get_movies
    self.movies.uniq
  end

  def get_theaters
    self.theaters.uniq
  end

  def earliest_showtime
    self.selections.order('time').first.time
  end

  def outing_emails!
    schedule_result_email unless self.result_date == nil
    send_invite_email
  end

  def posters
    self.movies.uniq[0..2].map {|movie| movie.poster_med}
  end

  def result_date_in_timezone
    theater_id = self.selections.first.theater_id

    zipcode = Zipcode.joins(:theaters).where('theaters.id = ?', theater_id).first.zipcode
    string_timezone = ActiveSupport::TimeZone.find_by_zipcode(zipcode)

    self.result_date.in_time_zone(string_timezone).strftime('%A, %b %d %-l:%M%P')
  end

  def save_result_date
    time = time_until_earliest_showtime
    if time > 6
      self.result_date = self.earliest_showtime - 6.hours
      self.save
    elsif time <= 6 and time > 3
      self.result_date = self.earliest_showtime - 3.hours
      self.save
    end

  end

  def schedule_result_email
    EmailWorker.perform_at(self.result_date, self.user_id, self.id, 'result')
  end

  def send_invite_email
    EmailWorker.perform_async(self.user_id, self.id, 'invite')
  end

  def time_until_earliest_showtime
    (self.earliest_showtime - Time.now) / 3600
  end

  def top_selections
    self.selections.order('selected_count DESC').limit(3)
  end

  private
  def generate_link
    self.link = SecureRandom.hex(3)
  end

  def create_selections
    showtimes.each do |showtime|
      self.selections.build(showtime: showtime,
                               movie: showtime.movie,
                               time: showtime.time,
                               theater: showtime.theater)
    end
  end
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController

  def cache
    set_current_zipcode params[:zipcode]
    zipcode = Zipcode.find_or_create_by_zipcode(current_zipcode)
    fetch_new_show_times(zipcode) and return if zipcode.stale?
    redirect_to new_outing_path
  end

  def new
    @outing = Outing.new
    @zipcode = Zipcode.find_by_zipcode(current_zipcode)
    @movies = @zipcode.movies
    @days = day_range(current_timezone_string)
  end


  def create
    showtimes = available_showtimes
    if flash[:notice]
      return redirect_to new_outing_path
    end
    outing = Outing.new(user: current_user, :showtimes => showtimes)
    if outing.save
      session[:outing_id] = outing.id
      redirect_to '/success'
    else
      render :new
    end
  end

  def loading
  end

  def status
    if session[:jids]
      @jids = session[:jids]
      completed = @jids.all?{ |jid| Sidekiq::Status.status(jid) == :complete}
      session[:jids].clear if completed
      Zipcode.where(:zipcode => session[:zipcode]).first.update_cache_date!
      render :json => {status: completed.to_s}
    else
      render :json => {status: completed.to_s}
    end
  end

  def success
    if session[:outing_id]
      @outing = Outing.find(session.delete(:outing_id))
      render :show
    else
      redirect_to root_path
    end
  end

end

app/views/outings/_form.html.erb
<!-- <div id="select-movie">
  <div class="row">
    <div class="large-12 columns">
      <div id="select">
        <h1 style='text-align:center;'>CREATE A MOVIE EVENT</h1>
        <p style='text-align:center;'>ZIPCODE: <%= current_zipcode %></p>
        <h2>STEP 1. SELECT MOVIES</h2>
      </div>
    </div>
  </div>
</div> -->

<div class="hero">
  <div class="row">
    <div class="large-12 columns">
      <div class="">
        <h1>CREATE A MOVIE EVENT</h1>
        <p>ZIPCODE: <%= current_zipcode %></p>
        <div class="wheel-1"></div>
      </div>
    </div>
  </div>
</div>

<div class="sub-hero">
  <div class="row">
    <div class="large-12 columns">
      <div class="">
        <h3>STEP 1. SELECT MOVIES</h3>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <%= form_for @outing, :html => {:class => "marquee"} do |f| %>
      <div id="movie-marquee-wrapper">
        <div id="movie-marquee" class="movie-marquee">
          <ul>
          <% @movies.each_with_index do |movie, index| %>
            <% index += 1 %>
            <% movie_poster = movie.poster || default_poster %> 
            <!-- default poster is a helper method -->
            <% checkbox = check_box_tag(movie.title, movie.id, checked = false, name: "movies[#{movie.title}]") %>
            <% if index <= 8 %>
              <% label = label_tag(movie.title, nil, :class => 'panel', :style => "background-image: url(#{movie_poster})", :data => {:image_url => movie_poster}) %>
            <% else %>
              <% label = label_tag(movie.title, nil, :class => 'panel', :data => {:image_url => movie_poster}) %>
            <% end %>
            <% if (index) % 4 == 1 %>
              <li>
                <div class='poster'>
                  <span class="check"><i class="icon-ok"></i></span>
                  <%= checkbox %>
                  <%= label %>
                  <div class="movie-info-tool-tip tool-tip-right">
                    <div class="movie-info-wrapper">
                    <%= render 'tooltip_info', movie: movie %>
                      <span class="arrow-left"><i class="icon-caret-left"></i></span>
                    </div>
                  </div>
                </div>
            <% elsif (index) % 4 == 0 %>
              <div class='poster'>
                <span class="check"><i class="icon-ok"></i></span>
                <%= checkbox %>
                <%= label %>
                <div class="movie-info-tool-tip tool-tip-left">
                  <div class="movie-info-wrapper">
                   <%= render 'tooltip_info', movie: movie %>
                    <span class="arrow-right"><i class="icon-caret-right"></i></span>
                  </div>
                </div>
              </div>
            </li>
            <% elsif (index) % 4 == 3 %>
              <div class='poster'>
                <span class="check"><i class="icon-ok"></i></span>
                <%= checkbox %>
                <%= label %>
                <div class="movie-info-tool-tip tool-tip-left">
                  <div class="movie-info-wrapper">
                    <%= render 'tooltip_info', movie: movie %>
                    <span class="arrow-right"><i class="icon-caret-right"></i></span>
                  </div>
                </div>
              </div>
            <% elsif (index) % 4 == 2 %>
              <div class='poster'>
                <span class="check"><i class="icon-ok"></i></span>
                <%= checkbox %>
                <%= label %>
                <div class="movie-info-tool-tip tool-tip-right">
                  <div class="movie-info-wrapper">
                    <%= render 'tooltip_info', movie: movie %>
                    <span class="arrow-left"><i class="icon-caret-left"></i></span>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>

          <% if @movies.length % 4 == 0 %>
            </li>
          <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>

  <div id="day-time-container">
    <div class="row">
      <div class="large-12 columns">
        <div id="select">
          <h3>STEP 2. SELECT A DAY AND TIME</h3>
        </div>
      </div>
    </div>
    <div class="row">
      <div id="day-time">
        <%= render 'outings/time_selects' %>
      </div>
    </div>
    <div class="row">
      <div class='large-12 columns'>
        <div id="create">
          <span id='login-errors'></span>
          <%= f.submit "CREATE EVENT", :class => "button" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<script>
  jQuery( document ).ready( function ( $ ) {

    $(document).click(function() {
      $('.wrapper-dropdown').removeClass('active');
    });

    function DropDown( el, select, indexStart) {
      this.dd = el;
      this.sel = select;
      this.indexStart = indexStart
      this.placeholder = this.dd.children( 'span' );
      this.opts = this.dd.find( 'ul.dropdown > li' );
      this.val = '';
      this.index = -1;
      this.initEvents();
    }

    DropDown.prototype = {
      initEvents : function() {
        var obj = this;
 
        obj.dd.on('click', function(event){
            $(this).toggleClass('active');
            return false;
        });
 
        obj.opts.on('click',function(){
          var opt = $(this);
          obj.val = opt.text();
          // Index starts at 8, so this must start at 8
          obj.index = opt.index() + obj.indexStart;
          obj.placeholder.text( obj.val );
          obj.sel.val(obj.index);
        });
      },
      getValue : function() {
        return this.val;
      },
      getIndex : function() {
        return this.index;
      }
    }

    var day = new DropDown( $( '#day-dd' ), $( '#day' ), 0 );
    var start = new DropDown( $( '#start-dd' ), $( '#start_time' ), 8 );
    var end = new DropDown( $( '#end-dd' ), $( '#end_time' ), 8 );

  });
</script>

app/views/outings/_time_selects.html.erb
<div class='large-2 columns'>
  <span class="showing">STARTING</span>
</div>
<div class='large-2 columns'>
  <%= select_tag(:day, options_for_select(@days))%>
  <div id="day-dd" class="wrapper-dropdown" tabindex="1">
    <span>TODAY</span>
    <ul class="dropdown">
        <% @days.each do |day| %>
        <li><a href="#"><%= day[0] %></a></li>
        <% end %>
    </ul>
  </div>
</div>
<div class='large-2 columns between'>
  <span class="between">BETWEEN</span>
</div>
<div class='large-2 columns'>
  <%= select_tag(:start_time, options_for_select(time_range)) %>
  <div id="start-dd" class="wrapper-dropdown" tabindex="1">
    <span>8AM</span>
    <ul class="dropdown">
        <% time_range.each do |time| %>
        <li><a href="#"><%= time[0] %></a></li>
        <% end %>
    </ul>
  </div>
</div>
<div class='large-2 columns between'>
  <span class="between">AND</span>
</div>
<div class='large-2 columns'>
  <%= select_tag(:end_time, options_for_select(time_range)) %>
  <div id="end-dd" class="wrapper-dropdown" tabindex="1">
    <span>8AM</span>
    <ul class="dropdown">
        <% time_range.each do |time| %>
        <li><a href="#"><%= time[0] %></a></li>
        <% end %>
    </ul>
  </div>
</div>

app/views/outings/_tooltip_info.html.erb
<div>
  <h4><%= movie.title %></h4>
</div>
<div>
  Rated <%= movie.mpaa_rating %>
</div>
<div>
  <%= hours_minutes(movie.runtime) %>
</div>
<div>
  Critics Score: <%= movie.critics_score %>
</div>
<div>
  Audience Score: <%= movie.audience_score %>
</div>

app/views/outings/loading.html.erb
<div class='loading-page'>
  <h3 class='loading-status'>We're preparing your showtimes, watch a trailer while you wait!</h3>
  <div id="player"></div>

  <script src="http://www.youtube.com/player_api"></script>

  <script>

    var jobState = false;

    function addReadyMessage(){
      $('.loading-status').html('All ready! Click <%= link_to "HERE", new_outing_path %>.')
    }

    function longPoll(){
      var i = setInterval(function(){
        $.post('/status')
        .done(function(data){
          console.log(data)
          if(data.status === 'true'){
            clearInterval(i);
            jobState = true;
            addReadyMessage();
          }
        }).fail(function(){
          console.log('something went wrong');
        })
      },5000)
    }

    longPoll();

    var videos = ['dQw4w9WgXcQ', 'CNfiXZzmhjw', 'wArmHSPIvlQ', 'QAEkuVgt6Aw', 'MUrL7GcgHO0', 'IctcdgbksZ4', 'koNSa_6Fd1U', 'MKIXQdv4G7o'];
    var randVideo = videos[Math.floor(Math.random() * videos.length)];

    // create youtube player
    var player;
    function onYouTubePlayerAPIReady() {
      player = new YT.Player('player', {
        height: '400',
        width: '640',
        videoId: randVideo,
        events: {
          'onReady': onPlayerReady,
          'onStateChange': onPlayerStateChange
        }
      });
    }

    // autoplay video
    function onPlayerReady(event) {
      event.target.playVideo();
    }

    // when video ends
    function onPlayerStateChange(event) {
      if(event.data === 0 && jobState === true) {
        window.location = "<%= new_outing_path %>"
      }
    }
  </script>
</div>

app/views/outings/new.html.erb
<%= render 'outings/form' %>

app/views/outings/show.html.erb
<div class="thank-you">
  <br>
  <h1>Success!</h1>
  <h3>We emailed you an invite to share with your friends.</h3>
  <h4>Or if you prefer, share this link: <%= link_to outings_form_url(@outing.link),outings_form_url(@outing.link) %></h4>
  <br>
  <% if @outing.result_date %>
    <p>We will send you results on <strong><%= @outing.result_date_in_timezone %></strong></p>
    <p>Be sure to poll your friends before then. Happy watching!</p>
  <% end %>
    <br>
  <h3> - Dash, The Movie Dino </h3>

</div>